-- MycoField: "a spot near you" — email + postcode during the free look pins today's nearest scanned spot for
-- that email. It opens only when that same email is signed in with access (from £2 a week). Paste all of it
-- into Supabase → SQL Editor → Run. Safe to run again. Needs spots.sql / credits.sql (live_spots, current_scan).
create table if not exists public.lead_spots (email text primary key, postcode text not null, spot_lat double precision not null, spot_lon double precision not null, spot_name text, region text, nation text, habitat text, score smallint, km real, scanned_on date, created_at timestamptz not null default now(), opened_at timestamptz);
alter table public.lead_spots enable row level security;
revoke all on public.lead_spots from anon, authenticated;
-- Called before sign-in with the postcode's centre (the app looks it up on postcodes.io). Returns only the teaser:
-- score, distance, county. One spot per email per week: asking again gives the same answer.
create or replace function public.lead_spot(p_email text, p_postcode text, p_lat double precision, p_lon double precision) returns table (score smallint, km real, region text, nation text, habitat text, postcode text) language plpgsql security definer set search_path = public as $$ declare e text := lower(trim(p_email)); pc text := upper(left(regexp_replace(trim(p_postcode), '\s+', ' ', 'g'), 10)); d date := public.current_scan(); s record; begin if e !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' or length(e) > 200 then raise exception 'bad_email'; end if; if p_lat is null or p_lon is null or p_lat not between 49.8 and 61 or p_lon not between -8.7 and 2 then raise exception 'bad_postcode'; end if; if exists (select 1 from public.lead_spots l where l.email = e and l.created_at > now() - interval '7 days') then return query select l.score, l.km, l.region, l.nation, l.habitat, l.postcode from public.lead_spots l where l.email = e; return; end if; if (select count(*) from public.lead_spots l where l.created_at > now() - interval '1 hour') >= 300 then raise exception 'busy'; end if; if d is null then raise exception 'no_spots'; end if; select ls.lat, ls.lon, ls.name, ls.region, ls.nation, ls.habitat, ls.score, round((6371 * 2 * asin(sqrt(power(sin(radians(ls.lat - p_lat) / 2), 2) + cos(radians(p_lat)) * cos(radians(ls.lat)) * power(sin(radians(ls.lon - p_lon) / 2), 2))))::numeric, 1) as km into s from public.live_spots ls where ls.scanned_on = d order by 8 limit 1; if not found then raise exception 'no_spots'; end if; insert into public.lead_spots (email, postcode, spot_lat, spot_lon, spot_name, region, nation, habitat, score, km, scanned_on) values (e, pc, s.lat, s.lon, s.name, s.region, s.nation, s.habitat, s.score, s.km, d) on conflict (email) do update set postcode = excluded.postcode, spot_lat = excluded.spot_lat, spot_lon = excluded.spot_lon, spot_name = excluded.spot_name, region = excluded.region, nation = excluded.nation, habitat = excluded.habitat, score = excluded.score, km = excluded.km, scanned_on = excluded.scanned_on, created_at = now(), opened_at = null; return query select s.score::smallint, s.km::real, s.region, s.nation, s.habitat, pc; end $$;
revoke all on function public.lead_spot(text, text, double precision, double precision) from public;
grant execute on function public.lead_spot(text, text, double precision, double precision) to anon, authenticated;
-- After sign-in: the spot pinned for this account's own email, only with access. Nothing pinned → no rows.
create or replace function public.open_lead_spot() returns table (lat double precision, lon double precision, name text, score smallint, postcode text, km real) language plpgsql security definer set search_path = public as $$ declare uid uuid := auth.uid(); e text; begin if uid is null then raise exception 'sign_in_required' using errcode = '42501'; end if; select lower(u.email) into e from auth.users u where u.id = uid; if not exists (select 1 from public.lead_spots l where l.email = e and l.created_at > now() - interval '14 days') then return; end if; if not exists (select 1 from public.entitlements en where en.user_id = uid and en.paid_until > now()) then raise exception 'access_required'; end if; update public.lead_spots l set opened_at = coalesce(l.opened_at, now()) where l.email = e; return query select l.spot_lat, l.spot_lon, l.spot_name, l.score, l.postcode, l.km from public.lead_spots l where l.email = e; end $$;
revoke all on function public.open_lead_spot() from public, anon;
grant execute on function public.open_lead_spot() to authenticated;
select 'lead spots ready' as status;
